### ISSUE TITLE
RSS downloads auto sort

### ISSUE THREAD

**Issue by undeadmecha0** [Sam-Max/rcmltb#125]
Automated rclone files sorter after each upload is finished.
Like > rclone copy *One Piece --ignore-case "Bot Storage:Downloads" "Gdrive:Airing/[Erai-Raws] One Piece" --include .mkv --exclude *

Idk if this script works but this is how i visualized it
This script can be attached to qbit everytime a download finished.

I don't mind doing individual rclone copy script for every show but i know you can do it more efficiently with parser

**Comment by Sam-Max** [comment]
> 

I don't understand well what you want.

**Comment by Sam-Max** [comment]
closing this
