### ISSUE TITLE
Add onedrive index url support

### ISSUE THREAD

**Issue by sobuj53** [Sam-Max/rcmltb#130]
Hi there,

Thank you for this wonderful repo. Could you please add Onedrive index link support? [repo link](https://github.com/spencerwooo/onedrive-vercel-index). Thank you for considering my request.

**Comment by Sam-Max** [comment]
> Hi there,
> 
> Thank you for this wonderful repo. Could you please add Onedrive index link support? [repo link](https://github.com/spencerwooo/onedrive-vercel-index). Thank you for considering my request.

Hi, you can use /serve command to create an index of onedrive with bot

**Comment by sobuj53** [comment]
Thank you for your response. However, I was suggesting something like `OD_INDEX_URL = ""`. I already have the index deployed and I was hoping that, once a file has been uploaded to OD, it will directly return the file link from the index as `Cloud Link 🔗`. Something like this had been implement [here](https://github.com/yash-dk/TorToolkit-Telegram/blob/bbe21858588c0dc004ffcc2d0f8845c28e02371d/tortoolkit/config/ExecVarsSample.py#L72).

**Comment by Sam-Max** [comment]
> 

How do you generate the one drive index? Which tool?

**Comment by sobuj53** [comment]
If you meant how to deploy the index, then the guide can be found [here](https://ovi.swo.moe/docs/getting-started). If you meant how link generation will work then,

say my index url is, `https://drive.swo.moe` upload folder is, `/Shared files` and the uploaded file name is, `genshin-impact-npc-scene-interaction.mp4`, then the index link will be, `https://drive.swo.moe/Shared%20files/genshin-impact-npc-scene-interaction.mp4`

**Comment by Sam-Max** [comment]
> 
I will add a button after upload to cloud with the link to the file from the rclone serve index, that way will work with any cloud, not just onedrive.

**Comment by sobuj53** [comment]
Thank you for taking the time to work on this issue. However, there are few downfalls to this solution. 

1. The index needs to be started first.
2. It creates strain on the VPS CPU. 

While the solution is really elegant, I think it could stay as an alternative solution and I would kindly ask you to consider adding support for dedicated index link.

Thank you for considering.
